// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: QRcode

#include "ui.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

static int current_screen = 0;

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();
    ui_setting_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home);


}

void ui_destroy(void)
{
    ui_home_screen_destroy();
    ui_setting_screen_destroy();
}

/**
 * Event handler for gesture
 */
void screen_gesture_event(lv_event_t *e)
{
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_active());
    
    switch(dir) {
         case LV_DIR_LEFT:
            if(current_screen == 0) {
                if(qr_obj) {
                lv_obj_delete(qr_obj);
                qr_obj = NULL;
        }
        lv_scr_load_anim(ui_setting,
                         LV_SCR_LOAD_ANIM_MOVE_LEFT,
                         50,
                         0,
                         false);
 
                current_screen = 1;
            }
        break;

        case LV_DIR_RIGHT:
            if(current_screen == 1) {
        lv_scr_load_anim(ui_home,
                         LV_SCR_LOAD_ANIM_MOVE_RIGHT,
                         50,
                         0,
                         false);
                lv_async_call(qr_task, NULL);
                lv_label_set_text(ui_Label6, LV_SYMBOL_SETTINGS " SETTING ");
                current_screen = 0;
            }
        break;
            
        case LV_DIR_TOP:
        case LV_DIR_BOTTOM:
            break;
    }
}