// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: QRcode

#ifndef _QRCODE_UI_H
#define _QRCODE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "string.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

///////////////////// SCREENS ////////////////////

#include "ui_home.h"
#include "ui_setting.h"
#include "qr_webserver.h"


///////////////////// VARIABLES ///////////////////

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);
void screen_gesture_event(lv_event_t *e);
void wifi_item_event_handler(lv_event_t * e);
void wifi_scan_task(void * pvParameters);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
