// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: QRcode

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_StatusBar;
extern lv_obj_t * ui_wifistatus;
extern lv_obj_t * ui_QRarea;
extern lv_obj_t * qr_obj;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_wifiState;
extern lv_color_t ui_qr_color;
extern lv_color_t  ui_qr_bg_color;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

