// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: QRcode

#include "ui.h"

lv_obj_t * ui_home = NULL;
lv_obj_t * ui_StatusBar = NULL;
lv_obj_t * ui_wifistatus = NULL;
lv_obj_t * ui_QRarea = NULL;
lv_obj_t * ui_wifiState = NULL;
lv_obj_t * ui_Battery = NULL;


// event funtions
// build funtions

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusBar = lv_obj_create(ui_home);
    lv_obj_set_width(ui_StatusBar, 236);
    lv_obj_set_height(ui_StatusBar, 34);
    lv_obj_set_x(ui_StatusBar, 0);
    lv_obj_set_y(ui_StatusBar, -140);
    lv_obj_set_align(ui_StatusBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_StatusBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifistatus = lv_label_create(ui_StatusBar);
    lv_obj_set_width(ui_wifistatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifistatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifistatus, "--:--");
    lv_obj_set_style_text_font(ui_wifistatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_wifistatus, 2, 0);

    ui_wifiState = lv_label_create(ui_StatusBar);
    lv_obj_set_width(ui_wifiState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiState, -91);
    lv_obj_set_y(ui_wifiState, 0);
    lv_obj_set_align(ui_wifiState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiState, LV_SYMBOL_WARNING);
    lv_obj_set_style_text_font(ui_wifiState, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery = lv_label_create(ui_StatusBar);
    lv_obj_set_width(ui_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery, 94);
    lv_obj_set_y(ui_Battery, 0);
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Battery, LV_SYMBOL_BATTERY_FULL);
     lv_obj_set_style_text_font(ui_Battery, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QRarea = lv_obj_create(ui_home);
    lv_obj_set_width(ui_QRarea, 231);
    lv_obj_set_height(ui_QRarea, 251);
    lv_obj_set_x(ui_QRarea, -1);
    lv_obj_set_y(ui_QRarea, 17);
    lv_obj_set_align(ui_QRarea, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_QRarea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


lv_obj_add_event_cb(ui_home, screen_gesture_event, 
                    LV_EVENT_GESTURE, NULL);

}


void ui_home_screen_destroy(void)
{
    if(ui_home) lv_obj_del(ui_home);

    // NULL screen variables
    ui_home = NULL;
    ui_StatusBar = NULL;
    ui_wifistatus = NULL;
    ui_QRarea = NULL;
    ui_wifiState = NULL;
    ui_Battery = NULL;
    qr_obj = NULL;


}
