// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: QRcode


#include "ui.h"

lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_brightness = NULL;
lv_obj_t * ui_adjBrightness = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_bright = NULL;
lv_obj_t * ui_wifiScan = NULL;
lv_obj_t * ui_btnConnect = NULL;
lv_obj_t * ui_WifiScantxt = NULL;
lv_obj_t * ui_Sttbar = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_WifiList = NULL;
lv_obj_t * ui_pwd_input = NULL;
lv_obj_t * ui_pwd_textarea = NULL;

char selected_ssid[64];

extern void TFT_SET_BL(uint8_t Value);

extern void start_wifi_scan(void);   // forward declare
extern void start_wifi_connect(const char * ssid, const char * password);

extern lv_obj_t * wifi_list; 

// event funtions
void ui_event_adjBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        int32_t value = lv_slider_get_value(target);
        lv_label_set_text_fmt(ui_Label2, "%d%%", value);
        TFT_SET_BL((uint8_t)value);
    }
}

void ui_event_btnConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_add_flag(ui_brightness, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_wifiScan, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_WifiList, LV_OBJ_FLAG_HIDDEN);
        lv_label_set_text(ui_Label6, LV_SYMBOL_REFRESH " Scanning...");
        start_wifi_scan(); 
    }
}

/** Hide WiFi list */
static void hide_wifi_list(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_CLICKED) {
        lv_indev_t * indev = lv_indev_get_act();
        lv_point_t point;
        lv_indev_get_point(indev, &point);

        lv_area_t panel_area;
        lv_obj_get_coords(ui_WifiList, &panel_area);

        bool inside = (point.x >= panel_area.x1 &&
                       point.x <= panel_area.x2 &&
                       point.y >= panel_area.y1 &&
                       point.y <= panel_area.y2);

        if(!inside) {
            lv_obj_add_flag(ui_WifiList, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_WifiList, LV_OBJ_FLAG_EVENT_BUBBLE);
            lv_obj_clear_flag(ui_brightness, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_wifiScan, LV_OBJ_FLAG_HIDDEN);
        }
    }
}
void keyboard_outside_click(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_CLICKED) {
        lv_indev_t * indev = lv_indev_get_act();
        lv_point_t point;
        lv_indev_get_point(indev, &point);

        // get coords of keyboard
        lv_area_t kb_area;
        lv_obj_get_coords(ui_Keyboard1, &kb_area);

        // get coords of pwd panel
        lv_area_t pwd_area;
        lv_obj_get_coords(ui_pwd_input, &pwd_area);

        bool inside_kb = (point.x >= kb_area.x1 && point.x <= kb_area.x2 &&
                          point.y >= kb_area.y1 && point.y <= kb_area.y2);

        bool inside_pwd = (point.x >= pwd_area.x1 && point.x <= pwd_area.x2 &&
                           point.y >= pwd_area.y1 && point.y <= pwd_area.y2);

        if(!inside_kb && !inside_pwd) {
            lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
            lv_obj_remove_event_cb(ui_setting, keyboard_outside_click);
            lv_obj_clear_flag(ui_brightness, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_wifiScan, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_pwd_input, LV_OBJ_FLAG_HIDDEN);
        }
    }
}
/** Event handler for password connect button */
void pwd_connect_event(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_CLICKED) {
        const char * password = lv_textarea_get_text(ui_pwd_textarea);

        // Ẩn keyboard + pwd panel
        lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_pwd_input, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_brightness, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_wifiScan, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_event_cb(ui_setting, keyboard_outside_click);

        // call wifi connect function  (expose from lvgl_port.cpp)
        start_wifi_connect(selected_ssid, password);
    }
}
/** Event handler for WiFi list items */
void wifi_item_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target_obj(e);

    if(code == LV_EVENT_CLICKED) {
        // save ssid to global variable
        const char * ssid = lv_list_get_button_text(wifi_list, obj);
        strncpy(selected_ssid, ssid, sizeof(selected_ssid) - 1);

        // update label in pwd panel
        lv_obj_t * label = lv_obj_get_child(ui_pwd_input, 0);
        lv_label_set_text(label, ssid);

        // del
        lv_textarea_set_text(ui_pwd_textarea, "");

        // hiđen wifi list, show keyboard + pwd panel
        lv_obj_add_flag(ui_WifiList, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_pwd_input, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);

        //register event to hide keyboard when click outside
        lv_obj_add_event_cb(ui_setting, keyboard_outside_click, LV_EVENT_CLICKED, NULL);
    }
}
// build funtions

void ui_setting_screen_init(void)
{
    ui_setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_setting);
    lv_obj_set_width(ui_Keyboard1, 234);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 96);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags

    ui_brightness = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_brightness, 231);
    lv_obj_set_height(ui_brightness, 68);
    lv_obj_set_x(ui_brightness, -1);
    lv_obj_set_y(ui_brightness, -50);
    lv_obj_set_align(ui_brightness, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_brightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_adjBrightness = lv_slider_create(ui_brightness);
    lv_slider_set_value(ui_adjBrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_adjBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_adjBrightness, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_adjBrightness, 150);
    lv_obj_set_height(ui_adjBrightness, 11);
    lv_obj_set_x(ui_adjBrightness, -20);
    lv_obj_set_y(ui_adjBrightness, 10);
    lv_obj_set_align(ui_adjBrightness, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_adjBrightness, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_adjBrightness,
                                                                                                    lv_obj_get_style_pad_right(ui_adjBrightness, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label2 = lv_label_create(ui_brightness);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 90);
    lv_obj_set_y(ui_Label2, 10);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "0");

    ui_bright = lv_label_create(ui_brightness);
    lv_obj_set_width(ui_bright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bright, 0);
    lv_obj_set_y(ui_bright, -18);
    lv_obj_set_align(ui_bright, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bright, "Brightness");
    lv_obj_set_style_text_font(ui_bright, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiScan = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_wifiScan, 233);
    lv_obj_set_height(ui_wifiScan, 78);
    lv_obj_set_x(ui_wifiScan, -2);
    lv_obj_set_y(ui_wifiScan, 58);
    lv_obj_set_align(ui_wifiScan, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnConnect = lv_button_create(ui_wifiScan);
    lv_obj_set_width(ui_btnConnect, 110);
    lv_obj_set_height(ui_btnConnect, 35);
    lv_obj_set_x(ui_btnConnect, 2);
    lv_obj_set_y(ui_btnConnect, 2);
    lv_obj_set_align(ui_btnConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiScantxt = lv_label_create(ui_btnConnect);
    lv_obj_set_width(ui_WifiScantxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiScantxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiScantxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiScantxt, "Wifi Scan");

    ui_Sttbar = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_Sttbar, 237);
    lv_obj_set_height(ui_Sttbar, 34);
    lv_obj_set_x(ui_Sttbar, -1);
    lv_obj_set_y(ui_Sttbar, -141);
    lv_obj_set_align(ui_Sttbar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Sttbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Sttbar);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6,LV_SYMBOL_SETTINGS " SETTING ");

    ui_WifiList = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_WifiList, 228);
    lv_obj_set_height(ui_WifiList, 266);
    lv_obj_set_x(ui_WifiList, -1);
    lv_obj_set_y(ui_WifiList, 15);
    lv_obj_set_align(ui_WifiList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiList, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_WifiList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /** Password Input ui */
    ui_pwd_input = lv_obj_create(ui_setting);
    lv_obj_set_size(ui_pwd_input, 228, 130);
    lv_obj_set_align(ui_pwd_input, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_pwd_input, -40);
    lv_obj_add_flag(ui_pwd_input, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);

    // Label tên wifi
    lv_obj_t * ssid_label = lv_label_create(ui_pwd_input);
    lv_label_set_text(ssid_label, "");
    lv_obj_set_align(ssid_label, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ssid_label, LV_OBJ_FLAG_USER_1); // đánh dấu để tìm lại

    // Textarea nhập mật khẩu
    ui_pwd_textarea = lv_textarea_create(ui_pwd_input);
    lv_obj_set_size(ui_pwd_textarea, 180, 36);
    lv_obj_set_align(ui_pwd_textarea, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_pwd_textarea, 18);
    lv_textarea_set_password_mode(ui_pwd_textarea, true);
    lv_textarea_set_placeholder_text(ui_pwd_textarea, "Password");
    lv_textarea_set_one_line(ui_pwd_textarea, true);

    // Add textarea to keyboard
    lv_keyboard_set_textarea(ui_Keyboard1, ui_pwd_textarea);

    // Connect
    lv_obj_t * btn_connect = lv_button_create(ui_pwd_input);
    lv_obj_set_size(btn_connect, 80, 30);
    lv_obj_set_align(btn_connect, LV_ALIGN_BOTTOM_MID);
    

    lv_obj_t * btn_label = lv_label_create(btn_connect);
    lv_label_set_text(btn_label, "Connect");
    lv_obj_center(btn_label);

    lv_obj_add_event_cb(ui_adjBrightness, ui_event_adjBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnConnect, ui_event_btnConnect, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_setting, screen_gesture_event, 
                        LV_EVENT_GESTURE, NULL);

    lv_obj_add_event_cb(ui_setting, hide_wifi_list, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(btn_connect, pwd_connect_event, LV_EVENT_CLICKED, NULL);
}

void ui_setting_screen_destroy(void)
{
    if(ui_setting) lv_obj_del(ui_setting);

    // NULL screen variables
    ui_setting = NULL;
    ui_Keyboard1 = NULL;
    ui_brightness = NULL;
    ui_adjBrightness = NULL;
    ui_Label2 = NULL;
    ui_bright = NULL;
    ui_wifiScan = NULL;
    ui_btnConnect = NULL;
    ui_WifiScantxt = NULL;
    ui_Sttbar = NULL;
    ui_Label6 = NULL;
    ui_WifiList = NULL;
    ui_pwd_input = NULL;
    ui_pwd_textarea = NULL;
    ui_Keyboard1 = NULL;

}
