// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: QRcode

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_brightness;
extern void ui_event_adjBrightness(lv_event_t * e);
extern lv_obj_t * ui_adjBrightness;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_bright;
extern lv_obj_t * ui_wifiScan;
extern void ui_event_btnConnect(lv_event_t * e);
extern lv_obj_t * ui_btnConnect;
extern lv_obj_t * ui_WifiScantxt;
extern lv_obj_t * ui_Sttbar;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_WifiList;
extern lv_obj_t * ui_pwd_input;
extern lv_obj_t * ui_pwd_textarea;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

